name: Firebase Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          cd firebase-functions
          npm install

      - name: Authenticate to Google Cloud
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/google-application-credentials.json

      - name: Set up Google Cloud credentials
        run: gcloud auth activate-service-account --key-file=$HOME/google-application-credentials.json

      - name: Deploy to Firebase
        run: |
          firebase use --add
          firebase deploy --only functions,hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/google-application-credentials.json

      - name: Clean up
        run: rm -f $HOME/google-application-credentials.json
